In [6]:
import numpy as np
import math

l = 0.46 # m
theta = 35 * math.pi / 180 # radians
theta_dot = np.array([[5.0]]) # m/s
theta_ddot = np.array([[2.0]]) # m/s^2

J = np.array([
    [-l * math.sin(theta)],
    [l * math.cos(theta)]
])

H_dot = np.dot(J, theta_dot)
H_dot

array([[-1.3192258],
       [ 1.8840497]])

In [7]:
Jdot = np.array([
    [-l * math.cos(theta) * theta_dot[0, 0]],
    [-l * math.sin(theta) * theta_dot[0, 0]]
])

H_ddt = np.dot(Jdot, theta_dot)+np.dot(J, theta_ddot)
H_ddt

array([[-9.94793883],
       [-5.84250914]])

In [9]:
J1 = np.linalg.pinv(J)
J1

array([[-1.2469053 ,  1.78076531]])